import Head from "next/head";
import { Header } from "@components/index";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ceedcap Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  );
}
